image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Android SDK
    init: |
      chmod +x gradlew
      ./gradlew assembleDebug
    command: |
      echo "APK built successfully!"

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java 